export type AuthStackParamList = {
  SignUp: undefined;
  Login: undefined;
  FinishSetup: undefined;
  School: undefined;
  NameAndPicture: undefined;
  Role: undefined;
  TeachingSubjects: undefined;
  CoursesForStudents: undefined;
  Experiences: undefined;
  Certificate: undefined;
  TeachingStyle: undefined;
  AvailableTimeSlots: undefined;
  MentorshipInterest: undefined;
  Interests: undefined;
  ClassLevel: undefined;
  LearningStyle: undefined;
  WelcomeScreen: undefined;
  LoadingScreen: undefined;
};
